### ISSUE TITLE
Files Reading and Uploading

### ISSUE THREAD

**Issue by mady143** [aahmad4/Resume-Scanner#4] opened 2020-04-15 04:24 UTC
Hi @aahmad4 ,

** I had an issue with my flask framework i was unable to upload the files from any where from the system i was unable to process to upload the files.
** and also facing the problem with reading the files like pdf, docx,doc files right now i am using the different conditions to read the particular files is their any option to read all types of files in single line of code with out condition..

Thanks and Regards,
Manikantha Sekhar..

**Comment by aahmad4** [comment] 2020-04-15 04:28
Hey @mady143 ,
Regarding reading different files, currently, the model was built just to accept word documents, and convert them to txt documents. To use pdf's and other doc types, I would suggest installing and importing the necessary modules to make those conversions possible. Could you please elaborate on what issues you had on your flask framework, regarding uploading files. I'll get back to you as soon as possible.

Best Regards,
Ali Ahmad

**Comment by mady143** [comment] 2020-04-15 05:14
Hi @aahmad4 ,
Thank you so much for response and patience actually my question is i am using flask framework and and working on the same task i.e., resume filtering actually i wrote an API that expalin how the resume and job description dynamically from the front end like 

![ssss](https://user-images.githubusercontent.com/37180858/79300581-c9c5c680-7f04-11ea-8bdb-4843f9f6e7cd.png)

like the above image i am trying to upload the files and get the output as per your result like getting the matching percentage

now while i was trying to upload the file from the system only where my .py is located from their its self only it was uploading means i am getting an error while uploading from the different location, getting an error  like 

![ddddd](https://user-images.githubusercontent.com/37180858/79300759-45277800-7f05-11ea-879e-6033b4ecde49.png)

and my code looks like 
.py and html bellow please open and look once you may understand 
![1](https://user-images.githubusercontent.com/37180858/79300965-dc8ccb00-7f05-11ea-8cc9-6475c7fc49da.png)
![2](https://user-images.githubusercontent.com/37180858/79300968-df87bb80-7f05-11ea-8b36-e7b1c92555a8.png)
![3](https://user-images.githubusercontent.com/37180858/79300971-e1ea1580-7f05-11ea-8561-86afbfc0e483.png)
![4](https://user-images.githubusercontent.com/37180858/79300974-e282ac00-7f05-11ea-8584-91fa503d0cdd.png)

these are 4 screen shots i have sent all the files expect the output html file 

please let me know if your confused and please help me to resolve this issue.

Thanks and Regards,
Manikantha Sekhar.

**Comment by aahmad4** [comment] 2020-04-15 05:24
Hi @mady143 ,
This is not an issue related to my program so I don't know the exact answer.  However, I would look into the documentation for reading PDF files on Python, as that seems to be what you're having trouble with. Also in some instances, these conversions require the full path, rather than just the filename.pdf (.pdf as an example). Definitely, look into the documentation for those, and there should be some Python libraries for them, and you should have a good idea of what the problem is. I will now close this issue as it's not related to my program, but I wish you good luck.

Best Regards,
Ali Ahmad

**Closed by aahmad4** 2020-04-15 05:24 UTC
